
exports.up = function (knex, Promise) {
    return knex.schema.createTable('actives', table => {
        table.increments('id').primary()
        table.integer('batchId').references('id')
            .inTable('batchs').notNull()
        table.string('placa').notNull()
        table.string('anexo').notNull()
        table.integer('costCId').references('id')
            .inTable('costCenters').notNull()
        table.integer('localId').references('id')
            .inTable('locals').notNull()
        table.string('descriptionDefault', 1000)
        table.integer('descriptionId').references('id')
            .inTable('descriptions').notNull()
        table.string('complemento')
        table.string('marca')
        table.string('modelo')
        table.string('numSerie').notNull()
        table.string('dimensao')
        table.string('capacidade')
        table.integer('useConditionId').references('id')
            .inTable('useConditions').notNull()
        table.string('tag').notNull()
        table.integer('responsibleId').references('id')
            .inTable('responsibles').notNull()
        table.integer('projectId').references('id')
            .inTable('projects').notNull()
        table.integer('unitBusId').references('id')
            .inTable('unitBusiness').notNull()
        table.integer('groupId').references('id')
            .inTable('groupings').notNull()
        table.integer('numAntigo')
        table.integer('anoFabricacao')
        table.string('observacao')
        table.string('imageURL', 1000)
        table.integer('userId').references('id')
            .inTable('users').notNull()
    })
};

exports.down = function (knex, Promise) {
    return knex.schema.dropTable('actives')
};
