
exports.up = function(knex, Promise) {
    return knex.schema.createTable('actives', table => {
        table.increments('id').primary()
        table.integer('batchId').references('id')
            .inTable('batchs')
        table.integer('empresaId').references('id')
            .inTable('clients')
        table.integer('placa').notNull()
        table.string('anexo').notNull()
        table.integer('costCenterId').references('id')
            .inTable('costCenters').notNull()
        table.integer('localId').references('id')
            .inTable('locals').notNull()
        table.integer('descriptionId').references('id')
            .inTable('descriptions').notNull()
        table.string('description', 1000)
        table.string('complemento')
        table.string('marca')
        table.string('modelo')
        table.string('numSerie')
        table.string('dimensao')
        table.string('capacidade')
        table.integer('useConditionId').references('id')
            .inTable('useConditions').notNull()
        table.string('tag')
        table.integer('responsibleId').references('id')
            .inTable('responsibles')
        table.integer('projectId').references('id')
            .inTable('projects')
        table.integer('unitBusId').references('id')
            .inTable('unitBusiness')
        table.integer('groupingId').references('id')
            .inTable('groupings')
        table.string('numAntigo')
        table.string('anoFabricacao')
        table.string('observacao')
        table.string('imageURL', 1000)
        table.integer('userId').references('id')
            .inTable('users')
    })      
};

exports.down = function(knex, Promise) {
    return knex.schema.dropTable('actives')  
};
